## Types of Loss Functions

In [1]:
# Loss functions ?
# Cost function ?
# y-y_predicted is the error
# error at each itration is called as 'Loss'
# Genralize total error is colled as cost function
# There are four mostly used loss functions:
# 1.Mean absolute error(mean_absolute_error)
# 2.Mean squared error(mean_squared_error)
# 3.Log loss or binary cross entropy(binary_crossentropy)
# 4.(sparce_categorical_crossentropy)
# 5.(categorical_cross_entropy)
# link: https://towardsdatascience.com/common-loss-functions-in-machine-learning-46af0ffc4d23

In [2]:
# Why we not use MSE for logistic regression:
# link: https://towardsdatascience.com/why-not-mse-as-a-loss-function-for-logistic-regression-589816b5e03c

In [3]:
import numpy as np
y_true = np.array([1,0,0,1,1,0,1])
y_predicted = np.array([0.89,0.4,0,0.91,1,0,0.92])

## 1. MSE

In [4]:
# mean square error using pure python
def MSE(y_true,y_predicted):
    sum_of_error = 0
    for yt,yp in zip(y_true,y_predicted):              # we use zip instead of range as zip works parallely on both arrays
        sum_of_error += (yt - yp)**2
    MSE =  sum_of_error/len(y_true)   
    return MSE  

In [5]:
MSE(y_true,y_predicted)

0.02665714285714286

In [6]:
# mean square error using numpy in one line
np.mean(np.square(y_true-y_predicted))

0.02665714285714286

## 2. MAE

In [7]:
# mean absolute error using pure python
def MAE(y_true,y_predicted):
    error = 0
    for yt,yp in zip(y_true,y_predicted):              # we use zip instead of range as zip works parallely on both arrays
         error += abs(yt - yp)
    MAE =  error/len(y_true)   
    return MAE  

In [8]:
MAE(y_true,y_predicted)

0.09714285714285713

In [9]:
# mean absolute error using numpy in one line
np.mean(np.abs(y_predicted-y_true))

0.09714285714285713

## 3. LogLoss Or Binary_crossentropy

In [10]:
# Log loss or Binary cross entropy
np.log([0])

<ipython-input-10-98cdf1d7085f>:2: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [11]:
epsilon = 1e-15
np.log([epsilon])

array([-34.53877639])

In [12]:
np.log([1])

array([0.])

In [13]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[0.89, 0.4, 1e-15, 0.91, 1.0, 1e-15, 0.92]

In [14]:
1-epsilon

0.999999999999999

In [15]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.89, 0.4, 1e-15, 0.91, 0.999999999999999, 1e-15, 0.92]

In [16]:
y_predicted_new = np.array(y_predicted_new)
np.log(y_predicted_new)


array([-1.16533816e-01, -9.16290732e-01, -3.45387764e+01, -9.43106795e-02,
       -9.99200722e-16, -3.45387764e+01, -8.33816089e-02])

In [17]:
# Using numpy
log_loss = -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))
log_loss

0.11500738977603393

In [18]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [19]:
log_loss(y_true, y_predicted)

0.11500738977603393